version: "3.8"

services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8081:8080"
    # volumes:
    #   - ./trino/etc:/etc/trino
    networks:
      - analytics-net
    restart: unless-stopped

networks:
  analytics-net:
