version: '3.8'

networks:
  default:
  metastore:
    external: true
    name: metastore_metastore

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"  # Access DBeaver on http://localhost:8978
    volumes:
      - ./data:/opt/cloudbeaver/workspace
    environment:
      - CB_INIT_CONFIGURATION_FILE=/opt/cloudbeaver/workspace/init-config.conf
    restart: unless-stopped
    networks:
      - default
      - metastore
