version: '3.8'

networks:
  default:
  metastore:
    external: true
    name: metastore_metastore
  
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}           
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin1234}    
    volumes:
      - ./data:/data                
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - default
      - metastore
