version: "3"

services:
  kafka:
    image: bitnami/kafka:latest
    user: root
    ports:
      - "9092:9092"   # Internal listener for internal containers/VPC
      - "9093:9093"   # Controller listener
      - "9094:9094"   # External listener for public access
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=my-cluster-id-123
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      # MULTI-LISTENER CONFIG
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://${PUBLIC_DOMAIN:-0.0.0.0}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # # OPTIONAL: Allow topic auto-creation (good for dev, toggle off in strict prod)
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

      # Required for PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

    volumes:
      - ./kafka-data:/bitnami/kafka
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    volumes:
      - ./kafkaui/config.yml:/etc/kafkaui/config.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/etc/kafkaui/config.yml 
    depends_on:
      - kafka
    networks:
      - kafka-net

networks:
  kafka-net:
